var kihong = "<strong>Kihong Heo</strong>"
var mayur = "<a href=\"http://www.cis.upenn.edu/~mhnaik\">Mayur Naik</a>"
var rajeev = "<a href=\"http://www.cis.upenn.edu/~alur/home.html\">Rajeev Alur</a>"
var mukund = "<a href=\"https://www.cis.upenn.edu/~rmukund\">Mukund Raghothaman</a>"
var hakjoo = "<a href=\"http://prl.korea.ac.kr/~pronto/home\">Hakjoo Oh</a>"
var hongseok = "<a href=\"https://sites.google.com/view/hongseokyang/home\">Hongseok Yang</a>"
var woosuk = "<a href=\"http://ropas.snu.ac.kr/~wslee\">Woosuk Lee</a>"
var kwang = "<a href=\"http://ropas.snu.ac.kr/~kwang\">Kwangkeun Yi</a>"

var pubs = [
  {
    title: "Resource-aware Program Analysis via Online Abstraction Coarsening",
    author: [kihong, hakjoo, hongseok],
    venue: '<a href="https://2019.icse-conferences.org">ICSE 2019: 41st ACM/IEEE International Conference on Software Engineering</a>',
    year: 2019,
    paper: "paper/icse19.pdf",
    type: "conference"
  },
  {
    title: "Effective Program Debloating via Reinforcement Learning",
    author: [kihong, woosuk, "Pardis Pashakhanloo", mayur],
    cofirst: [0, 1],
    venue: '<a href="https://www.sigsac.org/ccs/CCS2018">CCS 2018: ACM Conference on Computer and Communications Security</a>',
    year: 2018,
    paper: "paper/ccs18.pdf",
    slides: "slide/ccs18-slides.pdf",
    code: "https://github.com/aspire-project/chisel",
    video: "https://youtu.be/8eRZKoLFakw",
    type: "conference"
  },
  {
    title: "User-Guided Program Reasoning using Bayesian Inference",
    author: [mukund, "Sulekha Kulkarni", kihong, mayur],
    venue: '<a href="https://conf.researchr.org/home/pldi-2018">PLDI 2018: Programming Language Design and Implementation</a>',
    year: 2018,
    paper: "paper/pldi18-rakuhena.pdf",
    full: "paper/pldi18a-full.pdf",
    bib: "https://dblp.uni-trier.de/rec/bibtex/conf/pldi/RaghothamanKHN18",
    type: "conference"
  },
  {
    title: "Accelerating Search-Based Program Synthesis Using Learned Probabilistic Models",
    author: [woosuk, kihong, rajeev, mayur],
    venue: '<a href="https://conf.researchr.org/home/pldi-2018">PLDI 2018: Programming Language Design and Implementation</a>',
    year: 2018,
    paper: "paper/pldi18-lehealna.pdf",
    bib: "https://dblp.uni-trier.de/rec/bibtex/conf/pldi/LeeHAN18",
    code: "https://github.com/wslee/euphony",
    type: "conference"
  },
  {
    title: "Difflog: Beyond Deductive Methods in Program Analysis",
    author: [mukund, "Sulekha Kulkarni", "Richard Zhang", "Xujie Si", kihong, woosuk, mayur],
    venue: '<a href="http://ml4p.org">ML4P: 1st Workshop on Machine Learning for Programming</a>',
    year: 2018,
    paper: "paper/ml4p18.pdf",
    type: "workshop"
  },
  {
    title: "Learning Analysis Strategies for Octagon and Context Sensitivity from Labeled Data Generated by Static Analyses",
    author: [kihong, hakjoo, hongseok],
    venue: '<a href="https://link.springer.com/article/10.1007%2Fs10703-017-0306-7">FMSD: Formal Methods in System Design</a> (<b>Invited Paper</b>)',
    year: 2018,
    toappear: '(to appear)',
    paper: "paper/fmsd18-heohya.pdf",
    type: "journal"
  },
  {
    title: "Adapting Static Analysis via Learning with Bayesian Optimization",
    author: [kihong, hakjoo, hongseok, kwang],
    venue: '<a href="http://toplas.acm.org">TOPLAS: ACM Transactions on Programming Languages and Systems</a>',
    year: 2018,
    toappear: '(to appear)',
    paper: "paper/toplas17-heohyayi.pdf",
    type: "journal"
  },
  {
    title: "Machine-Learning-Guided Selectively Unsound Static Analysis",
    author: [kihong, hakjoo, kwang],
    venue: '<a href="http://icse2017.gatech.edu">ICSE 2017: The 39th International Conference on Software Engineering</a>',
    year: 2017,
    paper: "paper/icse17-heohyi.pdf",
    bib: "http://dblp.uni-trier.de/rec/bibtex/conf/icse/HeoOY17",
    slides: "slide/icse17-slides.pdf",
    type: "conference"
  },
  {
    title: "Automatically Generating Features for Learning Program Analysis Heuristics",
    author: ["Kwonsoo Chae", hakjoo, kihong, hongseok],
    venue: '<a href="http://2017.splashcon.org/track/splash-2017-OOPSLA">OOPSLA 2017: ACM Conference on Object-Oriented Programming, Systems, Languages, and Applications</a>',
    year: 2017,
    paper: "paper/oopsla17-chohheya.pdf",
    bib: "http://dblp.uni-trier.de/rec/bibtex/journals/pacmpl/ChaeOHY17",
    type: "conference"
  },
  {
    title: "Selective Conjunction of Context-sensitivity and Octagon Domain toward Scalable and Precise Global Static Analysis",
    author: [kihong, hakjoo, kwang],
    venue: '<a href="http://onlinelibrary.wiley.com/journal/10.1002/(ISSN)1097-024X">SP&E: Software-Practice and Experience</a>',
    year: 2017,
    paper: "paper/spe17-heohyi.pdf",
    bib: "http://dblp.uni-trier.de/rec/bibtex/journals/spe/HeoOY17",
    type: "journal"
  },
  {
    title: "Sound Non-Statistical Clustering of Static Analysis Alarms",
    author: [woosuk, "Wonchan Lee", "Dongok Kang", kihong, hakjoo, kwang],
    venue: '<a href="http://toplas.acm.org">TOPLAS: ACM Transactions on Programming Languages and Systems</a>',
    year: 2017,
    paper: "paper/toplas17-lelekaheohyi.pdf",
    bib: "http://dblp.uni-trier.de/rec/bibtex/journals/toplas/LeeLKHOY17",
    type: "journal"
  },
  {
    title: "Learning a Variable-Clustering Strategy for Octagon from Labeled Data Generated by a Static Analysis",
    author: [kihong, hakjoo, hongseok],
    venue: '<a href="http://staticanalysis.org/sas2016/">SAS 2016: The 23rd Static Analysis Symposium</a>',
    year: 2016,
    paper: "paper/sas16-heohya.pdf",
    bib: "http://dblp.uni-trier.de/rec/bibtex/conf/sas/HeoOY16",
    slides: "slide/sas16-slides.pdf",
    type: "conference"
  },
  {
    title: "Selective X-Sensitive Analysis Guided by Impact Pre-Analysis",
    author: [hakjoo, "Wonchan Lee", kihong, hongseok, kwang],
    venue: '<a href="http://toplas.acm.org">TOPLAS: ACM Transactions on Programming Languages and Systems</a>',
    year: 2016,
    paper: "paper/toplas16-ohleheyayi.pdf",
    bib: "http://dblp.uni-trier.de/rec/bibtex/journals/toplas/OhLHYY16",
    type: "journal"
  },
  {
    title: "Widening with Thresholds via Binary Search",
    author: ["Sol Kim", kihong, hakjoo, kwang],
    venue: '<a href="http://onlinelibrary.wiley.com/journal/10.1002/(ISSN)1097-024X">SP&E: Software-Practice and Experience</a>',
    year: 2016,
    paper: "paper/spe16-kiheohyi.pdf",
    bib: "http://dblp.dagstuhl.de/rec/bibtex/journals/spe/KimHOY16",
    type: "journal"
  },
  {
    title: "Selective Context-Sensitivity Guided by Impact Pre-Analysis",
    author: [hakjoo, "Wonchan Lee", kihong, hongseok, kwang],
    venue: '<a href="http://conferences.inf.ed.ac.uk/pldi2014/">PLDI 2014: The 35th ACM SIGPLAN Conference of Programming Language Design and Implementation</a>',
    year: 2014,
    paper: "paper/pldi14-ohleheyayi.pdf",
    full: "paper/pldi14-long-ohleheyayi.pdf",
    bib: "http://dblp.uni-trier.de/rec/bibtex/conf/pldi/OhLHYY14",
    type: "conference"
  },
  {
    title: "Global Sparse Analysis Framework",
    author: [hakjoo, kihong, "Wonchan Lee", woosuk, "Daejun Park", "Jeehoon Kang", kwang],
    venue: '<a href="http://toplas.acm.org">TOPLAS: ACM Transactions on Programming Languages and Systems</a>',
    year: 2014,
    paper: "paper/toplas14-ohhelelepakayi.pdf",
    bib: "http://dblp.uni-trier.de/rec/bibtex/journals/toplas/OhHLLPKY14",
    type: "journal"
  },
  {
    title: "A Sparse Evaluation Technique for Detailed Semantic Analyses",
    author: ["Yoonseok Ko", kihong, hakjoo],
    venue: '<a href="http://www.sciencedirect.com/science/article/pii/S1477842414000323">Computer Languages, Systems, & Structures</a>',
    year: 2014,
    paper: "paper/comlan14-koheoh.pdf",
    bib: "http://dblp.uni-trier.de/rec/bibtex/journals/cl/KoHO14",
    type: "journal"
  },
  {
    title: "Design and Implementation of Sparse Global Analyses for C-like Languages",
    author: [hakjoo, kihong, "Wonchan Lee", woosuk, kwang],
    venue: '<a href="http://pldi12.cs.purdue.edu">PLDI 2012: The 33rd ACM SIGPLAN Conference of Programming Language Design and Implementation</a>',
    year: 2012,
    paper: "paper/pldi12-ohheleleyi.pdf",
    bib: "http://dblp.uni-trier.de/rec/bibtex/conf/pldi/OhHLLY12",
    type: "conference"
  }
]

function itemize(entry) {
  html = "<li>" + entry['title'] + "</li>";
  entry.author[entry.author.length - 1] = "and " + entry.author[entry.author.length - 1];
  if ('cofirst' in entry) {
    entry['cofirst'].forEach(function(idx) {
      entry['author'][idx] = entry['author'][idx] + "*";
    })
  }
  html += entry['author'].join(', ')
  html += "<br>";
  html += entry.venue;
  html += ", ";
  html += entry.year;
  if ('toappear' in entry) {
    html += ' '
    html += entry.toappear;
  }
  html += "<br>"
  if ('paper' in entry) {
    html += "[<a href=\"" + entry.paper + "\">paper</a>]";
  } else {
    html += "[paper]";
  }
  if ('full' in entry) {
    html += " [<a href=\"" + entry.full + "\">full-version</a>]";
  }
  if ('bib' in entry) {
    html += " [<a href=\"" + entry.bib + "\">bib</a>]";
  }
  if ('slides' in entry) {
    html += " [<a href=\"" + entry.slides + "\">slides</a>]";
  }
  if ('video' in entry) {
    html += " [<a href=\"" + entry.video + "\">video</a>]";
  }
  if ('code' in entry) {
    html += " [<a href=\"" + entry.code + "\">code</a>]";
  }
  html += "<br><br>"
  return html;
}

function write() {
  var section = document.getElementById("publication-section");
  var html = "[*Authors contributed equally.]<br>"
  html += "<h4>Conference Papers</h4>"
  html += "<ol>";
  pubs.forEach(function(entry) {
    if (entry['type'] == "conference") {
      html += itemize(entry);
    }
  })
  html += "</ol>";
  html += "<h4>Journal Papers</h4>"
  html += "<ol>";
  pubs.forEach(function(entry) {
    if (entry['type'] == "journal") {
      html += itemize(entry);
    }
  })
  html += "</ol>";
  html += "<h4>Workhop Papers</h4>"
  html += "<ol>";
  pubs.forEach(function(entry) {
    if (entry['type'] == "workshop") {
      html += itemize(entry);
    }
  })
  section.innerHTML = html + "</ol>";
}

write();
