var korean = "&#x1F1F0;&#x1F1F7;"
var talks = [
  {
    title: "Program Transformation for Reducing Software Complexity",
    venue: "Korea University",
    date: "07/09/2018",
    slides: "slide/chisel-ku.pdf"
  },
  {
    title: "User-Guided Program Reasoning using Bayesian Inference",
    venue: "KAIST",
    date: "07/06/2018",
    slides: "slide/bingo-kaist.pdf"
  },
  {
    title: "Interactive Alarm Ranking System using Bayesian Inference",
    venue: "Korea University",
    date: "01/04/2018",
    slides: "slide/bingo-ku.pdf"
  },
  {
    title: "Machine-Learning-Guided Selectively Unsound Static Analysis",
    venue: "Naver",
    date: "06/26/2017",
    slides: "slide/icse17-naver.pdf",
    video: "https://youtu.be/71rReJrf_6Q",
    korean: true
  },
  {
    title: "Machine-Learning-Guided Selectively Unsound Static Analysis",
    venue: 'Paper presentation, <a href="http://icse2017.gatech.edu">ICSE 2017</a>',
    date: "05/26/2017",
    slides: "slide/icse17-slides.pdf"
  },
  {
    title: "Selectively Sensitive Static Analysis by Impact Pre-analysis and Machine Learning",
    venue: "Ph.D. Defense",
    date: "05/02/2017",
    slides: "slide/thesis-slides.pdf",
    korean: true
  },
  {
    title: "Inferbo: Infer-based buffer-overrun analyzer",
    venue: "Korea University",
    date: "04/14/2017",
    slides: "slide/inferbo-ku.pdf",
    korean: true
  },
  {
    title: "Inferbo: Infer-based buffer-overrun analyzer",
    venue: "KAIST",
    date: "03/24/2017",
    slides: "slide/inferbo-kaist.pdf",
    korean: true
  },
  {
    title: "Selectively Sensitive Static Analysis by Impact Pre-analysis and Machine Learning",
    venue: '<a href="http://www.codemind.co.kr">Codemind</a>',
    date: "02/20/2017",
    slides: "slide/selective-codemind.pdf",
    korean: true
  },
  {
    title: "Learning a Variable-Clustering Strategy for Octagon from Labeled Data Generated by a Static Analysis",
    venue: 'Paper presentation, <a href="http://staticanalysis.org/sas2016/">SAS 2016</a>',
    date: "09/08/2016",
    slides: "slide/sas16-slides.pdf"
  },
  {
    title: "Sound, Precise & Scalable Static Analysis by Sparsity and Selectivity",
    venue: 'Poster session, <a href="http://www.math.nagoya-u.ac.jp/~garrigue/APLAS2014/">APLAS 2014</a>',
    date: "11/17/2014",
    poster: "paper/aplas14-poster.pdf"
  },
  {
    title: "Design and Implementation of Sparse Global Analyses for C-like Languagues",
    venue: 'Poster session, <a href="http://pldi12.cs.purdue.edu">PLDI 2012</a>',
    date: "06/12/2012",
    poster: "paper/pldi14-poster.pdf"
  }
]

function write() {
  var section = document.getElementById("talk-section");
  var html = "<ul>";
  talks.forEach(function(entry) {
    html += "<li>" + entry['title'] + ", ";
    html += entry.venue + ", "
    html += entry.date + ". "
    if ('slides' in entry)
      html += " [<a href=\"" + entry.slides + "\">slides</a>]";
    if ('poster' in entry)
      html += " [<a href=\"" + entry.poster + "\">poster</a>]";
    if ('video' in entry)
      html += " [<a href=\"" + entry.video + "\">video</a>]";
    if ('korean' in entry)
      html += " " + korean;
    html += "</li>";
  })
  section.innerHTML = html + "</ul>";
}

write();
