# this goes inside _config.yml. Change as required
url: https://www.cis.upenn.edu/
baseurl: ~kheo

navigation:
  - text: Home
    url: /
  - text: Projects
    url: /projects.html
  - text: Publications
    url: /publications.html
  - text: Talks
    url: /talks.html
  - text: Service
    url: /service.html
