# this goes inside _config.yml. Change as required
url: https://kihongheo.github.io
baseurl: ""

navigation:
  - text: Home
    url: /
  - text: Projects
    url: /projects.html
  - text: Publications
    url: /publications.html
  - text: Talks
    url: /talks.html
  - text: Recruitment
    url: /recruitment.html
  - text: Calendar
    url: /calendar.html
  - text: Blog
    url: https://prosys.kaist.ac.kr/posts/
  - text: PL-Wiki
    url: https://github.com/prosyslab/pl-wiki/wiki
  - text: ProsysLab
    url: https://prosys.kaist.ac.kr
