# this goes inside _config.yml. Change as required

navigation:
  - text: Home
    url: https://www.cis.upenn.edu/~kheo
  - text: Projects
    url: /projects.html
  - text: Publications
    url: /publications.html
  - text: Talks
    url: /talks.html
  - text: Service
    url: /service.html
