# this goes inside _config.yml. Change as required
url: https://kihongheo.github.io
baseurl: ""

navigation:
  - text: Home
    url: /
  - text: Projects
    url: /projects.html
  - text: Publications
    url: /publications.html
  - text: Talks
    url: /talks.html
  - text: Service
    url: /service.html
  - text: Recruitment
    url: /recruitment.html
  - text: Blog
    url: /blog.html
  - text: ProsysLab
    url: https://prosys.kaist.ac.kr
