- title: "PC member"
  venue: "TAPAS 2020: Workshop on Tools for Automatic Program Analysis"
  link: "https://2020.splashcon.org/home/tapas-2020"

- title: "ERC member"
  venue: "PLDI 2019: ACM Conference on Programming Language Design and Implementation"
  link: "https://conf.researchr.org/home/pldi-2019"

- title: "AEC member"
  venue: "SAS 2018: Static Analysis Symposium"
  link: "http://staticanalysis.org/sas2018/sas2018.html"
