- title: "PC member"
  venue: "ICSE"
  year: 2025
  link: "https://conf.researchr.org/home/icse-2025"

- title: "PC member"
  venue: "ICSE"
  year: 2024
  link: "https://conf.researchr.org/home/icse-2024"

- title: "PC member"
  venue: "SAS"
  year: 2024
  link: "https://2024.splashcon.org/home/sas-2024"

- title: "PC member"
  venue: "LCTES"
  year: 2024
  link: "https://pldi24.sigplan.org/home/LCTES-2024"

- title: "PC member"
  venue: "PLDI"
  year: 2023
  link: "https://pldi23.sigplan.org"

- title: "PC member"
  venue: "PLDI"
  year: 2022
  link: "https://pldi22.sigplan.org"

- title: "PC member"
  venue: "POPL"
  year: 2022
  link: "https://popl22.sigplan.org"

- title: "PC member"
  venue: "OOPSLA"
  year: 2022
  link: "https://2022.splashcon.org/track/splash-2022-oopsla"

- title: "PC member"
  venue: "SAS"
  year: 2022
  link: "https://2022.splashcon.org/home/sas-2022"

- title: "Others"
  venue: "FSE (SRC)"
  year: 2022
  link: "https://2022.esec-fse.org/track/fse-2022-student-research-competition"

- title: "Others"
  venue: "ECOOP (Doctoral Symposium)"
  year: 2022
  link: "https://2022.ecoop.org/track/ecoop-2022-doctoral-symposium"

- title: "PC member"
  venue: "APLAS"
  year: 2021
  link: "https://conf.researchr.org/home/aplas-2021"

- title: "PC member"
  venue: "SYNT"
  year: 2021
  link: "https://workshops.inf.ed.ac.uk/SYNT2021/index.html"

- title: "PC member"
  venue: "OCAML"
  year: 2021
  link: "https://icfp21.sigplan.org/home/ocaml-2021"

- title: "PC member"
  venue: "TAPAS"
  year: 2020
  link: "https://2020.splashcon.org/home/tapas-2020"

- title: "Others"
  venue: "PLDI (ERC)"
  year: 2019
  link: "https://conf.researchr.org/home/pldi-2019"

- title: "Others"
  venue: "ICSE (Virtualization Committee)"
  year: 2020
  link: "https://2020.icse-conferences.org"
