- title: "PC member"
  venue: "SAS 2022: 29th Static Analysis Symposium"
  link: "https://2022.splashcon.org/home/sas-2022"

- title: "PC member"
  venue: "ESEC/FSE 2022: The ACM Joint European Software Engineering Conference and Symposium on the Foundations of Software Engineering (Student Research Competetion)"
  link: "https://2022.esec-fse.org/track/fse-2022-student-research-competition"

- title: "PC member"
  venue: "ECOOP 2022: European Conference on Object-Oriented Programming (Doctoral Symposium)"
  link: "https://2022.ecoop.org/track/ecoop-2022-doctoral-symposium"

- title: "PC member"
  venue: "OOPSLA 2022: ACM Conference on Object-Oriented Programming, Systems, Languages, and Applications"
  link: "https://2022.splashcon.org/track/splash-2022-oopsla"

- title: "PC member"
  venue: "PLDI 2022: ACM Conference on Programming Language Design and Implementation"
  link: "https://pldi22.sigplan.org"

- title: "PC member"
  venue: "POPL 2022: ACM Symposium on Principles of Programming Languages"
  link: "https://popl22.sigplan.org"

- title: "PC member"
  venue: "APLAS 2021: Asian Symposium on Programming Languages and Systems"
  link: "https://conf.researchr.org/home/aplas-2021"

- title: "PC member"
  venue: "SYNT 2021: Workshop on Synthesis"
  link: "https://workshops.inf.ed.ac.uk/SYNT2021/index.html"

- title: "PC member"
  venue: "OCAML 2021: The OCaml Users and Developers Workshop"
  link: "https://icfp21.sigplan.org/home/ocaml-2021"

- title: "PC member"
  venue: "TAPAS 2020: Workshop on Tools for Automatic Program Analysis"
  link: "https://2020.splashcon.org/home/tapas-2020"

- title: "ERC member"
  venue: "PLDI 2019: ACM Conference on Programming Language Design and Implementation"
  link: "https://conf.researchr.org/home/pldi-2019"
