- title: "PC member"
  venue: "POPL 2021: ACM Symposium on Principles of Programming Languages"
  link: "https://popl22.sigplan.org"

- title: "PC member"
  venue: "APLAS 2021: Asian Symposium on Programming Languages and Systems"
  link: "https://conf.researchr.org/home/aplas-2021"

- title: "PC member"
  venue: "OCAML 2021: The OCaml Users and Developers Workshop"
  link: "https://icfp21.sigplan.org/home/ocaml-2021"

- title: "PC member"
  venue: "TAPAS 2020: Workshop on Tools for Automatic Program Analysis"
  link: "https://2020.splashcon.org/home/tapas-2020"

- title: "ERC member"
  venue: "PLDI 2019: ACM Conference on Programming Language Design and Implementation"
  link: "https://conf.researchr.org/home/pldi-2019"
